### ISSUE TITLE
failed to resolve 'com.github.arthurghazaryan:floatingactionmenu:1.0.0'

### ISSUE THREAD

**Issue by automatiq** [ArthurGhazaryan/floatingactionmenu#1]
Adding _compile 'com.github.arthurghazaryan:floatingactionmenu:1.0.0'_ at app's build.gradle and syncing caused an error _failed to resolve 'com.github.arthurghazaryan:floatingactionmenu:1.0.0'_.

Studio version is 2.3.1, gradle version is 3.3. 

Project's build.gradle file includes: 

```
allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
```

**Comment by arthur-ghazaryan** [comment]
@a13xsus Already fixed.
